### ISSUE TITLE
New rankings for Osekai Rankings

### ISSUE THREAD

**Issue by Tanza3D** [Osekai/osekai-wip#8]
PR will be made on Osekai/osekai repo for DB and scripts stuff.
- [x] Kudosu Rankings
- [x] Level rankings (total)
- [x] Level rankings (standard deviated)
- [x] Accuracy rankings (total)
- [x] Accuracy rankings (standard deviated)

**Comment by MaxOhn** [comment]
- Adding level, accuracy, and kudosu fields: https://github.com/Osekai/scripts-rust/commit/9fc956e77b141ffd0ff49c60ba3e51d0007cc496
- Adding values for each mode: https://github.com/Osekai/scripts-rust/commit/8fd326590578d224f410cf4583b86d783a0a5d10
- Reset accuracy on insufficient activity: https://github.com/Osekai/scripts-rust/commit/36e10e20bcbfa6a1f46526d1061bb10cf7f40c03

**Comment by Tanza3D** [comment]
what API values do those all send as?

**Comment by MaxOhn** [comment]
Added:
- `stdev_{acc/level}`
- `standard_{acc/level}`
- `taiko_{acc/level}`
- `ctb_{acc/level}`
- `mania_{acc/level}`
- `kudosu`

Removed:
- `total_pp`

**Comment by Tanza3D** [comment]
wait why's total pp gone
